package clases;
// Generated 15 nov. 2018, 20:05:46 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumne generated by hbm2java
 */
public class Alumne implements java.io.Serializable {

	private String dni;
	private Professor professor;
	private String nom;
	private Date dataN;
	private String diaC;
	private Double horaC;
	private String aprovat;
	private String baixa;
	private Set<Practiques> practiqueses = new HashSet(0);
	private Set<Examen> examens = new HashSet(0);

	public Alumne() {
	}

	public Alumne(String dni) {
		this.dni = dni;
	}

	public Alumne(String dni, Professor professor, String nom, Date dataN, String diaC, Double horaC, String aprovat,
			String baixa, Set<Practiques> practiqueses, Set<Examen> examens) {
		this.dni = dni;
		this.professor = professor;
		this.nom = nom;
		this.dataN = dataN;
		this.diaC = diaC;
		this.horaC = horaC;
		this.aprovat = aprovat;
		this.baixa = baixa;
		this.practiqueses = practiqueses;
		this.examens = examens;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDataN() {
		return this.dataN;
	}

	public void setDataN(Date dataN) {
		this.dataN = dataN;
	}

	public String getDiaC() {
		return this.diaC;
	}

	public void setDiaC(String diaC) {
		this.diaC = diaC;
	}

	public Double getHoraC() {
		return this.horaC;
	}

	public void setHoraC(Double horaC) {
		this.horaC = horaC;
	}

	public String getAprovat() {
		return this.aprovat;
	}

	public void setAprovat(String aprovat) {
		this.aprovat = aprovat;
	}

	public String getBaixa() {
		return this.baixa;
	}

	public void setBaixa(String baixa) {
		this.baixa = baixa;
	}

	public Set<Practiques> getPractiqueses() {
		return this.practiqueses;
	}

	public void setPractiqueses(Set<Practiques> practiqueses) {
		this.practiqueses = practiqueses;
	}

	public Set<Examen> getExamens() {
		return this.examens;
	}

	public void setExamens(Set<Examen> examens) {
		this.examens = examens;
	}

}
