package clases;
// Generated 15 nov. 2018, 20:05:46 by Hibernate Tools 5.2.11.Final

/**
 * Examen generated by hbm2java
 */
public class Examen implements java.io.Serializable {

	private ExamenId id;
	private Alumne alumne;
	private Float qualificacio;

	public Examen() {
	}

	public Examen(ExamenId id, Alumne alumne) {
		this.id = id;
		this.alumne = alumne;
	}

	public Examen(ExamenId id, Alumne alumne, Float qualificacio) {
		this.id = id;
		this.alumne = alumne;
		this.qualificacio = qualificacio;
	}

	public ExamenId getId() {
		return this.id;
	}

	public void setId(ExamenId id) {
		this.id = id;
	}

	public Alumne getAlumne() {
		return this.alumne;
	}

	public void setAlumne(Alumne alumne) {
		this.alumne = alumne;
	}

	public Float getQualificacio() {
		return this.qualificacio;
	}

	public void setQualificacio(Float qualificacio) {
		this.qualificacio = qualificacio;
	}

}
