package clases;
// Generated 15 nov. 2018, 20:05:46 by Hibernate Tools 5.2.11.Final

import java.util.Date;

/**
 * ExamenId generated by hbm2java
 */
public class ExamenId implements java.io.Serializable {

	private String dni;
	private Date data;

	public ExamenId() {
	}

	public ExamenId(String dni, Date data) {
		this.dni = dni;
		this.data = data;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExamenId))
			return false;
		ExamenId castOther = (ExamenId) other;

		return ((this.getDni() == castOther.getDni())
				|| (this.getDni() != null && castOther.getDni() != null && this.getDni().equals(castOther.getDni())))
				&& ((this.getData() == castOther.getData()) || (this.getData() != null && castOther.getData() != null
						&& this.getData().equals(castOther.getData())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37 * result + (getData() == null ? 0 : this.getData().hashCode());
		return result;
	}

}
