package clases;
// Generated 15 nov. 2018, 20:05:46 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Professor generated by hbm2java
 */
public class Professor implements java.io.Serializable {

	private String dni;
	private String nom;
	private Date dataI;
	private Set<Alumne> alumnes = new HashSet(0);

	public Professor() {
	}

	public Professor(String dni) {
		this.dni = dni;
	}

	public Professor(String dni, String nom, Date dataI, Set<Alumne> alumnes) {
		this.dni = dni;
		this.nom = nom;
		this.dataI = dataI;
		this.alumnes = alumnes;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDataI() {
		return this.dataI;
	}

	public void setDataI(Date dataI) {
		this.dataI = dataI;
	}

	public Set<Alumne> getAlumnes() {
		return this.alumnes;
	}

	public void setAlumnes(Set<Alumne> alumnes) {
		this.alumnes = alumnes;
	}

}
