package clases;
// Generated 15 nov. 2018, 20:05:46 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private String matricula;
	private String model;
	private Date dataC;
	private Integer km;
	private Set practiqueses = new HashSet(0);

	public Vehicle() {
	}

	public Vehicle(String matricula) {
		this.matricula = matricula;
	}

	public Vehicle(String matricula, String model, Date dataC, Integer km, Set practiqueses) {
		this.matricula = matricula;
		this.model = model;
		this.dataC = dataC;
		this.km = km;
		this.practiqueses = practiqueses;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Date getDataC() {
		return this.dataC;
	}

	public void setDataC(Date dataC) {
		this.dataC = dataC;
	}

	public Integer getKm() {
		return this.km;
	}

	public void setKm(Integer km) {
		this.km = km;
	}

	public Set getPractiqueses() {
		return this.practiqueses;
	}

	public void setPractiqueses(Set practiqueses) {
		this.practiqueses = practiqueses;
	}

}
